# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSerialPort
from PyQt5.QtCore import *
import serial, threading

global ser
ser = serial.Serial(
    port='COM8',\
    baudrate=115200, \
    parity=serial.PARITY_NONE, \
    stopbits=serial.STOPBITS_ONE, \
    bytesize=serial.EIGHTBITS, \
    timeout=1)

seq = []

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.counter1 = 0
        self.counter2 = 0
        self.counter3 = 0
        self.counter4 = 0
        self.counter5 = 0
        self.counter6 = 0

        self.flag1 = False
        self.flag2 = False
        self.flag3 = False
        self.flag4 = False
        self.flag5 = False
        self.flag6 = False
        self.t = ser.readline().decode('utf-8')

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(760, 560, 75, 23))
        self.stop_btn.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.stop_btn.setObjectName("stop_btn")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(650, 560, 75, 23))
        self.start_btn.setStyleSheet("background-color: rgb(85, 170, 127)")
        self.start_btn.setObjectName("start_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(700, 30, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(2)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(700, 90, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(2)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(700, 150, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(2)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(700, 210, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setLineWidth(2)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(700, 270, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setLineWidth(2)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(700, 330, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setLineWidth(2)
        self.label_6.setObjectName("label_6")
        self.pause_btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pause_btn_1.setGeometry(QtCore.QRect(880, 40, 75, 23))
        self.pause_btn_1.setObjectName("pause_btn_1")
        self.pause_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pause_btn_2.setGeometry(QtCore.QRect(880, 100, 75, 23))
        self.pause_btn_2.setObjectName("pause_btn_2")
        self.pause_btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pause_btn_3.setGeometry(QtCore.QRect(880, 160, 75, 23))
        self.pause_btn_3.setObjectName("pause_btn_3")
        self.pause_btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pause_btn_4.setGeometry(QtCore.QRect(880, 220, 75, 23))
        self.pause_btn_4.setObjectName("pause_btn_4")
        self.pause_btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pause_btn_5.setGeometry(QtCore.QRect(880, 280, 75, 23))
        self.pause_btn_5.setObjectName("pause_btn_5")
        self.pause_btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pause_btn_6.setGeometry(QtCore.QRect(880, 340, 75, 23))
        self.pause_btn_6.setObjectName("pause_btn_6")
        self.textBrowser = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 30, 531, 50))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 90, 531, 50))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(50, 150, 531, 50))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(50, 210, 531, 50))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(50, 270, 531, 50))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(50, 330, 531, 50))
        self.textBrowser_6.setObjectName("textBrowser_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop_btn.setText(_translate("MainWindow", "Стоп"))
        self.start_btn.setText(_translate("MainWindow", "Старт"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.pause_btn_1.setText(_translate("MainWindow", "PushButton"))
        self.pause_btn_2.setText(_translate("MainWindow", "PushButton"))
        self.pause_btn_3.setText(_translate("MainWindow", "PushButton"))
        self.pause_btn_4.setText(_translate("MainWindow", "PushButton"))
        self.pause_btn_5.setText(_translate("MainWindow", "PushButton"))
        self.pause_btn_6.setText(_translate("MainWindow", "PushButton"))

        self.add_functions()
        self.check_serial_event()

    def check_serial_event(self):
        serial_thread = threading.Timer(1, self.check_serial_event)
        if ser.is_open == True:
            serial_thread.start()
            if ser.in_waiting:
                t = ser.readline().decode('utf-8')
                t = t[:t.find(';')]
                print(t)
                # if t == "1":
                #     self.Pause1()
                #
                # if t == "2":
                #     self.Pause2()
                #
                # if t == "3":
                #     self.Pause3()
                #
                # if t == "4":
                #     self.Pause4()
                #
                # if t == "5":
                #     self.Pause5()
                #
                # if t == "6":
                #     self.Pause6()

    def add_functions(self):
        self.timer = QTimer(self.centralwidget)
        # # adding action to timer
        self.timer.timeout.connect(self.showTime)
        # # update the timer every tenth second
        self.timer.start(93)
        self.start_btn.clicked.connect(lambda: self.Start())
        self.stop_btn.clicked.connect(lambda: self.Reset())
        self.pause_btn_1.clicked.connect(lambda: self.Pause1())
        self.pause_btn_2.clicked.connect(lambda: self.Pause2())
        self.pause_btn_3.clicked.connect(lambda: self.Pause3())
        self.pause_btn_4.clicked.connect(lambda: self.Pause4())
        self.pause_btn_5.clicked.connect(lambda: self.Pause5())
        self.pause_btn_6.clicked.connect(lambda: self.Pause6())



    def Pause1(self):
        self.flag1 = False

    def Pause2(self):
        self.flag2 = False

    def Pause3(self):
        self.flag3 = False

    def Pause4(self):
        self.flag4 = False

    def Pause5(self):
        self.flag5 = False

    def Pause6(self):
        self.flag6 = False

    def Start(self):
        self.flag1 = True
        self.flag2 = True
        self.flag3 = True
        self.flag4 = True
        self.flag5 = True
        self.flag6 = True

    def Reset(self):
        self.flag1 = False
        self.flag2 = False
        self.flag3 = False
        self.flag4 = False
        self.flag5 = False
        self.flag6 = False

    def showTime(self):
        # checking if flag is true
        if self.flag1:
            self.counter1 += 1
        if self.flag2:
            self.counter2 += 1
        if self.flag3:
            self.counter3 += 1
        if self.flag4:
            self.counter4 += 1
        if self.flag5:
            self.counter5 += 1
        if self.flag6:
            self.counter6 += 1

    # getting text from count
        text1 = str(self.counter1 / 10)
        text2 = str(self.counter2 / 10)
        text3 = str(self.counter3 / 10)
        text4 = str(self.counter4 / 10)
        text5 = str(self.counter5 / 10)
        text6 = str(self.counter6 / 10)
    # showing text
        self.label.setText(text1)
        self.label_2.setText(text2)
        self.label_3.setText(text3)
        self.label_4.setText(text4)
        self.label_5.setText(text5)
        self.label_6.setText(text6)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
